services:
  - type: web
    name: app
    runtime: docker
    dockerContext: .
    dockerfilePath: Dockerfile
    repo: https://github.com/aademola1979/splice-backend.git
    region: oregon
    healthCheckPath: /
    plan: free